[2023-11-16T13:03:51.165+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Backend_run.run_docker_task scheduled__2023-02-08T00:00:00+00:00 [queued]>
[2023-11-16T13:03:51.260+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Backend_run.run_docker_task scheduled__2023-02-08T00:00:00+00:00 [queued]>
[2023-11-16T13:03:51.276+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-16T13:03:51.367+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): run_docker_task> on 2023-02-08 00:00:00+00:00
[2023-11-16T13:03:51.379+0000] {standard_task_runner.py:57} INFO - Started process 94 to run task
[2023-11-16T13:03:51.438+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Backend_run', 'run_docker_task', 'scheduled__2023-02-08T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp0_573zug']
[2023-11-16T13:03:51.447+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask run_docker_task
[2023-11-16T13:03:51.712+0000] {task_command.py:416} INFO - Running <TaskInstance: Backend_run.run_docker_task scheduled__2023-02-08T00:00:00+00:00 [running]> on host 9ae86e27dab2
[2023-11-16T13:03:51.904+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'run_docker_task', field 'command'. Template: 'sh ./run.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ./run.sh
[2023-11-16T13:03:51.930+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ./run.sh
[2023-11-16T13:03:51.970+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Backend_run, task_id=run_docker_task, execution_date=20230208T000000, start_date=20231116T130351, end_date=20231116T130351
[2023-11-16T13:03:52.006+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 69 for task run_docker_task (sh ./run.sh; 94)
[2023-11-16T13:03:52.036+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-16T13:03:52.208+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
