[2023-11-18T10:23:41.522+0000] {processor.py:157} INFO - Started process (PID=34) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:23:41.539+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:23:41.551+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:23:41.550+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:23:41.605+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:23:41.581+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 25
    start = DummyOperator(task_id = 'start', dag = dag)
    ^
IndentationError: unexpected indent
[2023-11-18T10:23:41.606+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:23:41.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.197 seconds
[2023-11-18T10:23:50.054+0000] {processor.py:157} INFO - Started process (PID=82) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:23:50.057+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:23:50.062+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:23:50.061+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:23:50.070+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:23:50.067+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 25
    start = DummyOperator(task_id = 'start', dag = dag)
    ^
IndentationError: unexpected indent
[2023-11-18T10:23:50.071+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:23:50.142+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.102 seconds
[2023-11-18T10:24:14.484+0000] {processor.py:157} INFO - Started process (PID=103) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:24:14.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:24:14.496+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:14.496+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:24:14.508+0000] {processor.py:839} INFO - DAG(s) dict_keys(['DAG-1']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:24:14.604+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:14.603+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-18T10:24:14.609+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:14.609+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-18T10:24:14.612+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:14.612+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-18T10:24:14.612+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:14.612+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:24:14.619+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:14.619+0000] {dag.py:2963} INFO - Creating ORM DAG for DAG-1
[2023-11-18T10:24:14.624+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:14.624+0000] {dag.py:3722} INFO - Setting next_dagrun for DAG-1 to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:24:14.638+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.165 seconds
[2023-11-18T10:24:44.943+0000] {processor.py:157} INFO - Started process (PID=158) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:24:44.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:24:44.950+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:44.949+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:24:44.959+0000] {processor.py:839} INFO - DAG(s) dict_keys(['DAG-1']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:24:44.981+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:44.980+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:24:44.994+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:24:44.994+0000] {dag.py:3722} INFO - Setting next_dagrun for DAG-1 to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:24:45.005+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.068 seconds
[2023-11-18T10:25:15.220+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:25:15.222+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:25:15.226+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:25:15.226+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:25:15.236+0000] {processor.py:839} INFO - DAG(s) dict_keys(['DAG-1']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:25:15.256+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:25:15.255+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:25:15.270+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:25:15.270+0000] {dag.py:3722} INFO - Setting next_dagrun for DAG-1 to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:25:15.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.069 seconds
[2023-11-18T10:25:45.467+0000] {processor.py:157} INFO - Started process (PID=268) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:25:45.469+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:25:45.473+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:25:45.472+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:25:45.489+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:25:45.482+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 11, in <module>
    dag = DAG(dag_id='wisdomise database',
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 493, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'wisdomise database' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-18T10:25:45.490+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:25:45.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.101 seconds
[2023-11-18T10:26:01.657+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:26:01.660+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:26:01.670+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:01.667+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:26:01.689+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:26:01.806+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:01.806+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-18T10:26:01.817+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:01.817+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-18T10:26:01.823+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:01.822+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-18T10:26:01.823+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:01.823+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:26:01.879+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:01.879+0000] {dag.py:2963} INFO - Creating ORM DAG for wisdomise_database
[2023-11-18T10:26:01.893+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:01.893+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:26:01.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.256 seconds
[2023-11-18T10:26:32.178+0000] {processor.py:157} INFO - Started process (PID=358) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:26:32.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:26:32.186+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:32.185+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:26:32.196+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:26:32.217+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:32.216+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:26:32.232+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:26:32.231+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:26:32.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.070 seconds
[2023-11-18T10:27:02.367+0000] {processor.py:157} INFO - Started process (PID=412) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:27:02.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:27:02.371+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:27:02.371+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:27:02.386+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:27:02.408+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:27:02.408+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:27:02.439+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:27:02.439+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:27:02.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.092 seconds
[2023-11-18T10:27:32.544+0000] {processor.py:157} INFO - Started process (PID=467) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:27:32.548+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:27:32.554+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:27:32.552+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:27:32.571+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:27:32.595+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:27:32.595+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:27:32.614+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:27:32.613+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:27:32.624+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.088 seconds
[2023-11-18T10:28:03.320+0000] {processor.py:157} INFO - Started process (PID=522) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:28:03.322+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:28:03.323+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:28:03.322+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:28:03.340+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:28:03.366+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:28:03.366+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:28:03.386+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:28:03.386+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:28:03.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.085 seconds
[2023-11-18T10:28:33.726+0000] {processor.py:157} INFO - Started process (PID=577) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:28:33.728+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:28:33.729+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:28:33.729+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:28:33.741+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:28:33.768+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:28:33.768+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:28:33.784+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:28:33.784+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:28:33.795+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.074 seconds
[2023-11-18T10:29:04.027+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:29:04.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:29:04.031+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:04.031+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:29:04.047+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:29:04.089+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:04.089+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:29:04.105+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:04.105+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:29:04.115+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.095 seconds
[2023-11-18T10:29:15.171+0000] {processor.py:157} INFO - Started process (PID=641) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:29:15.173+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:29:15.175+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:15.174+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:29:15.195+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:15.191+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 20, in <module>
    writng = DummyOperator(task_id = 'pyoperator_writing_api ', dag = dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'pyoperator_writing_api ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-18T10:29:15.196+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:29:15.224+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.061 seconds
[2023-11-18T10:29:37.823+0000] {processor.py:157} INFO - Started process (PID=695) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:29:37.826+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:29:37.828+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:37.827+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:29:37.852+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:37.846+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 20, in <module>
    writng = DummyOperator(task_id = 'pyritingapi ', dag = dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'pyritingapi ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-18T10:29:37.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:29:37.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.069 seconds
[2023-11-18T10:29:54.813+0000] {processor.py:157} INFO - Started process (PID=741) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:29:54.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:29:54.821+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:54.820+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:29:54.845+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:29:54.843+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 21, in <module>
    waiting = DummyOperator(task_id = 'pysensor ', dag = dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'pysensor ' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-11-18T10:29:54.845+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:29:54.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.059 seconds
[2023-11-18T10:30:06.595+0000] {processor.py:157} INFO - Started process (PID=744) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:30:06.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:30:06.601+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:30:06.599+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:30:06.637+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:30:06.634+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 21, in <module>
    waiting = DummyOperator(task_id = 'pysensor', dag = dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 812, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'pysensor' has already been added to the DAG
[2023-11-18T10:30:06.637+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:30:06.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.137 seconds
[2023-11-18T10:30:22.891+0000] {processor.py:157} INFO - Started process (PID=783) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:30:22.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:30:22.896+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:30:22.895+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:30:22.920+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:30:22.916+0000] {dagbag.py:443} ERROR - Failed to bag_dag: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 439, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 458, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 466, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: wisdomise_database. Faulty task: pyoperator_writing_api
[2023-11-18T10:30:22.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:30:22.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.071 seconds
[2023-11-18T10:30:47.356+0000] {processor.py:157} INFO - Started process (PID=808) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:30:47.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:30:47.360+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:30:47.360+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:30:47.414+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:30:47.509+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:30:47.508+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:30:47.524+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:30:47.524+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:30:47.541+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.197 seconds
[2023-11-18T10:31:17.883+0000] {processor.py:157} INFO - Started process (PID=863) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:31:17.885+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:31:17.886+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:17.885+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:31:17.904+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:31:17.937+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:17.937+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:31:17.954+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:17.953+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:31:17.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.090 seconds
[2023-11-18T10:31:32.220+0000] {processor.py:157} INFO - Started process (PID=911) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:31:32.222+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:31:32.223+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:32.223+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:31:32.239+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:31:32.331+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:32.330+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:31:32.345+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:32.345+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:31:32.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.144 seconds
[2023-11-18T10:31:59.054+0000] {processor.py:157} INFO - Started process (PID=964) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:31:59.056+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:31:59.058+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:59.057+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:31:59.071+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:31:59.086+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:59.086+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:31:59.099+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:31:59.099+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:31:59.110+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.062 seconds
[2023-11-18T10:32:21.671+0000] {processor.py:157} INFO - Started process (PID=987) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:32:21.673+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:32:21.675+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:21.674+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:32:21.687+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:32:21.770+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:21.770+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:32:21.783+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:21.783+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:32:21.794+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.128 seconds
[2023-11-18T10:32:35.349+0000] {processor.py:157} INFO - Started process (PID=1022) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:32:35.351+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:32:35.353+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:35.352+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:32:35.364+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:32:35.393+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:35.392+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:32:35.412+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:35.412+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:32:35.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.084 seconds
[2023-11-18T10:32:46.561+0000] {processor.py:157} INFO - Started process (PID=1030) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:32:46.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:32:46.566+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:46.566+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:32:46.599+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:32:46.617+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:46.617+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:32:46.638+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:46.638+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:32:46.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.096 seconds
[2023-11-18T10:32:47.593+0000] {processor.py:157} INFO - Started process (PID=1031) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:32:47.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:32:47.595+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:47.594+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:32:47.607+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:32:47.624+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:47.624+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:32:47.641+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:32:47.641+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:32:47.652+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.064 seconds
[2023-11-18T10:33:18.344+0000] {processor.py:157} INFO - Started process (PID=1086) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:33:18.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:33:18.349+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:33:18.348+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:33:18.377+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:33:18.462+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:33:18.462+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:33:18.478+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:33:18.478+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:33:18.489+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.153 seconds
[2023-11-18T10:33:48.740+0000] {processor.py:157} INFO - Started process (PID=1141) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:33:48.742+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:33:48.744+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:33:48.743+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:33:48.755+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:33:48.775+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:33:48.775+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:33:48.789+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:33:48.789+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:33:48.799+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.065 seconds
[2023-11-18T10:34:19.475+0000] {processor.py:157} INFO - Started process (PID=1196) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:34:19.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:34:19.478+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:34:19.478+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:34:19.490+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:34:19.513+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:34:19.513+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:34:19.562+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:34:19.561+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:34:19.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.111 seconds
[2023-11-18T10:34:49.844+0000] {processor.py:157} INFO - Started process (PID=1252) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:34:49.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:34:49.848+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:34:49.848+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:34:49.862+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:34:49.891+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:34:49.891+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:34:49.921+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:34:49.921+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:34:49.933+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.096 seconds
[2023-11-18T10:35:20.241+0000] {processor.py:157} INFO - Started process (PID=1307) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:35:20.243+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:35:20.244+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:35:20.244+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:35:20.257+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:35:20.301+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:35:20.300+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:35:20.321+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:35:20.321+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:35:20.361+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.125 seconds
[2023-11-18T10:35:50.683+0000] {processor.py:157} INFO - Started process (PID=1362) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:35:50.685+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:35:50.687+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:35:50.686+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:35:50.709+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:35:50.732+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:35:50.732+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:35:50.749+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:35:50.749+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:35:50.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.089 seconds
[2023-11-18T10:36:20.866+0000] {processor.py:157} INFO - Started process (PID=1417) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:36:20.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:36:20.872+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:36:20.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:36:20.889+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:36:20.927+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:36:20.927+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:36:20.949+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:36:20.948+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:36:20.960+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.103 seconds
[2023-11-18T10:36:51.098+0000] {processor.py:157} INFO - Started process (PID=1472) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:36:51.100+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:36:51.101+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:36:51.101+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:36:51.118+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:36:51.167+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:36:51.167+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:36:51.186+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:36:51.186+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:36:51.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.115 seconds
[2023-11-18T10:37:21.494+0000] {processor.py:157} INFO - Started process (PID=1527) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:37:21.497+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:37:21.499+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:37:21.498+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:37:21.514+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:37:21.545+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:37:21.545+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:37:21.562+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:37:21.562+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:37:21.573+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.089 seconds
[2023-11-18T10:37:51.872+0000] {processor.py:157} INFO - Started process (PID=1582) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:37:51.875+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:37:51.876+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:37:51.875+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:37:51.889+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:37:51.910+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:37:51.910+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:37:51.925+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:37:51.925+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:37:51.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.071 seconds
[2023-11-18T10:38:22.217+0000] {processor.py:157} INFO - Started process (PID=1638) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:38:22.220+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:38:22.222+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:38:22.221+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:38:22.239+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:38:22.262+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:38:22.262+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:38:22.278+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:38:22.278+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:38:22.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.092 seconds
[2023-11-18T10:38:52.529+0000] {processor.py:157} INFO - Started process (PID=1693) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:38:52.531+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:38:52.533+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:38:52.532+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:38:52.546+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:38:52.567+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:38:52.566+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:38:52.581+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:38:52.581+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:38:52.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.068 seconds
[2023-11-18T10:39:23.186+0000] {processor.py:157} INFO - Started process (PID=1749) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:39:23.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:39:23.191+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:39:23.190+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:39:23.207+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:39:23.230+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:39:23.230+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:39:23.258+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:39:23.258+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:39:23.269+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.092 seconds
[2023-11-18T10:39:53.343+0000] {processor.py:157} INFO - Started process (PID=1804) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:39:53.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:39:53.349+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:39:53.348+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:39:53.365+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:39:53.390+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:39:53.390+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:39:53.406+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:39:53.406+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:39:53.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.086 seconds
[2023-11-18T10:40:23.600+0000] {processor.py:157} INFO - Started process (PID=1859) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:40:23.605+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:40:23.609+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:40:23.607+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:40:23.637+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:40:23.663+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:40:23.663+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:40:23.679+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:40:23.678+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:40:23.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.105 seconds
[2023-11-18T10:40:54.071+0000] {processor.py:157} INFO - Started process (PID=1914) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:40:54.074+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:40:54.076+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:40:54.075+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:40:54.087+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:40:54.123+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:40:54.123+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:40:54.142+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:40:54.142+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:40:54.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.090 seconds
[2023-11-18T10:41:24.295+0000] {processor.py:157} INFO - Started process (PID=1969) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:41:24.303+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:41:24.309+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:41:24.305+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:41:24.338+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:41:24.367+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:41:24.367+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:41:24.384+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:41:24.383+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:41:24.395+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.105 seconds
[2023-11-18T10:41:54.629+0000] {processor.py:157} INFO - Started process (PID=2023) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:41:54.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:41:54.637+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:41:54.636+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:41:54.657+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:41:54.686+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:41:54.686+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:41:54.717+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:41:54.717+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:41:54.734+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.116 seconds
[2023-11-18T10:42:24.904+0000] {processor.py:157} INFO - Started process (PID=2079) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:42:24.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:42:24.907+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:42:24.907+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:42:24.918+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:42:24.959+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:42:24.958+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:42:24.978+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:42:24.978+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:42:24.990+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.091 seconds
[2023-11-18T10:42:55.411+0000] {processor.py:157} INFO - Started process (PID=2134) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:42:55.414+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:42:55.415+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:42:55.415+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:42:55.426+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:42:55.448+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:42:55.448+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:42:55.463+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:42:55.463+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:42:55.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.072 seconds
[2023-11-18T10:43:25.943+0000] {processor.py:157} INFO - Started process (PID=2188) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:43:25.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:43:25.947+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:43:25.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:43:25.959+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:43:25.983+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:43:25.983+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:43:26.000+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:43:26.000+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:43:26.010+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.072 seconds
[2023-11-18T10:43:56.445+0000] {processor.py:157} INFO - Started process (PID=2243) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:43:56.446+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:43:56.447+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:43:56.447+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:43:56.457+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:43:56.475+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:43:56.475+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:43:56.489+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:43:56.489+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:43:56.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.057 seconds
[2023-11-18T10:44:26.870+0000] {processor.py:157} INFO - Started process (PID=2298) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:44:26.871+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:44:26.871+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:44:26.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:44:26.876+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:44:26.890+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:44:26.890+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:44:26.905+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:44:26.905+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:44:26.915+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.047 seconds
[2023-11-18T10:44:57.217+0000] {processor.py:157} INFO - Started process (PID=2352) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:44:57.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:44:57.221+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:44:57.220+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:44:57.254+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:44:57.287+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:44:57.287+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:44:57.309+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:44:57.309+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:44:57.329+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.119 seconds
[2023-11-18T10:45:28.080+0000] {processor.py:157} INFO - Started process (PID=2407) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:45:28.082+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:45:28.084+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:45:28.083+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:45:28.100+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:45:28.138+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:45:28.138+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:45:28.157+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:45:28.157+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:45:28.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.115 seconds
[2023-11-18T10:45:38.615+0000] {processor.py:157} INFO - Started process (PID=2443) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:45:38.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:45:38.618+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:45:38.618+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:45:38.632+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:45:38.630+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from Core import *
  File "/opt/airflow/dags/Core.py", line 2, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'
[2023-11-18T10:45:38.633+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:45:38.649+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.041 seconds
[2023-11-18T10:46:09.211+0000] {processor.py:157} INFO - Started process (PID=2498) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:46:09.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:46:09.214+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:46:09.214+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:46:09.225+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:46:09.223+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from Core import *
  File "/opt/airflow/dags/Core.py", line 2, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'
[2023-11-18T10:46:09.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:46:09.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.037 seconds
[2023-11-18T10:46:39.843+0000] {processor.py:157} INFO - Started process (PID=2553) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:46:39.845+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:46:39.846+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:46:39.846+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:46:39.852+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:46:39.851+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from Core import *
  File "/opt/airflow/dags/Core.py", line 2, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'
[2023-11-18T10:46:39.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:46:39.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.032 seconds
[2023-11-18T10:47:10.128+0000] {processor.py:157} INFO - Started process (PID=2608) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:47:10.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:47:10.133+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:47:10.132+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:47:10.144+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:47:10.142+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from Core import *
  File "/opt/airflow/dags/Core.py", line 2, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'
[2023-11-18T10:47:10.145+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:47:10.166+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.047 seconds
[2023-11-18T10:47:40.418+0000] {processor.py:157} INFO - Started process (PID=2664) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:47:40.420+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:47:40.421+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:47:40.421+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:47:40.439+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:47:40.436+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from Core import *
  File "/opt/airflow/dags/Core.py", line 2, in <module>
    from binance.client import Client
ModuleNotFoundError: No module named 'binance'
[2023-11-18T10:47:40.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:47:40.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 0.055 seconds
[2023-11-18T10:48:11.132+0000] {processor.py:157} INFO - Started process (PID=2718) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:48:11.134+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:48:11.136+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:48:11.135+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:48:19.306+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:48:19.296+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from Core import *
  File "/opt/airflow/dags/Core.py", line 67, in <module>
    test_database_connection(engine)
NameError: name 'engine' is not defined
[2023-11-18T10:48:19.309+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:48:19.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 8.222 seconds
[2023-11-18T10:48:50.392+0000] {processor.py:157} INFO - Started process (PID=2803) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:48:50.395+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:48:50.397+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:48:50.396+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:48:53.960+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:48:53.956+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 6, in <module>
    from Core import *
  File "/opt/airflow/dags/Core.py", line 67, in <module>
    test_database_connection(engine)
NameError: name 'engine' is not defined
[2023-11-18T10:48:53.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:48:53.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.607 seconds
[2023-11-18T10:49:24.489+0000] {processor.py:157} INFO - Started process (PID=2863) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:49:24.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:49:24.493+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:49:24.492+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:49:28.777+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:49:28.786+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:49:28.783+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:49:28.787+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:49:28.812+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.331 seconds
[2023-11-18T10:49:59.875+0000] {processor.py:157} INFO - Started process (PID=2924) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:49:59.878+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:49:59.879+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:49:59.879+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:50:03.402+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:50:03.421+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:50:03.416+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:50:03.422+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:50:03.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.578 seconds
[2023-11-18T10:50:33.992+0000] {processor.py:157} INFO - Started process (PID=2985) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:50:33.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:50:33.996+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:50:33.995+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:50:38.654+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:50:38.687+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:50:38.679+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:50:38.691+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:50:38.721+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.746 seconds
[2023-11-18T10:51:09.011+0000] {processor.py:157} INFO - Started process (PID=3061) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:51:09.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:51:09.012+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:51:09.012+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:51:12.788+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:51:12.793+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:51:12.792+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:51:12.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:51:12.802+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.794 seconds
[2023-11-18T10:51:42.959+0000] {processor.py:157} INFO - Started process (PID=3141) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:51:42.960+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:51:42.960+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:51:42.960+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:51:46.466+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:51:46.479+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:51:46.476+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:51:46.479+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:51:46.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.543 seconds
[2023-11-18T10:52:17.513+0000] {processor.py:157} INFO - Started process (PID=3211) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:52:17.516+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:52:17.517+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:52:17.517+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:52:22.072+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:52:22.090+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:52:22.087+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:52:22.090+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:52:22.108+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.601 seconds
[2023-11-18T10:52:52.725+0000] {processor.py:157} INFO - Started process (PID=3283) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:52:52.728+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:52:52.730+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:52:52.729+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:52:56.212+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:52:56.228+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:52:56.225+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:52:56.230+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:52:56.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.537 seconds
[2023-11-18T10:53:17.793+0000] {processor.py:157} INFO - Started process (PID=3333) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:53:17.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:53:17.797+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:53:17.796+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:53:22.532+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:53:22.544+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:53:22.542+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:53:22.545+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:53:22.571+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.784 seconds
[2023-11-18T10:53:53.147+0000] {processor.py:157} INFO - Started process (PID=3405) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:53:53.148+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:53:53.150+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:53:53.149+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:53:57.065+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:53:57.086+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:53:57.082+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:53:57.087+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:53:57.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.976 seconds
[2023-11-18T10:54:27.187+0000] {processor.py:157} INFO - Started process (PID=3467) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:54:27.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:54:27.191+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:54:27.190+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:54:31.223+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:54:31.244+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:54:31.237+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 41, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:54:31.245+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:54:31.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.124 seconds
[2023-11-18T10:54:49.776+0000] {processor.py:157} INFO - Started process (PID=3517) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:54:49.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:54:49.784+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:54:49.783+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:54:54.126+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:54:54.147+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:54:54.143+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 44, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:54:54.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:54:54.173+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.403 seconds
[2023-11-18T10:54:55.593+0000] {processor.py:157} INFO - Started process (PID=3535) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:54:55.596+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:54:55.598+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:54:55.597+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:55:00.498+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:55:00.530+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:55:00.526+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 43, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:55:00.537+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:55:00.628+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 5.044 seconds
[2023-11-18T10:55:30.862+0000] {processor.py:157} INFO - Started process (PID=3595) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:55:30.865+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:55:30.870+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:55:30.869+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:55:34.653+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:55:34.667+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:55:34.664+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 43, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:55:34.668+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:55:34.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.881 seconds
[2023-11-18T10:55:45.887+0000] {processor.py:157} INFO - Started process (PID=3632) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:55:45.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:55:45.902+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:55:45.896+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:55:51.955+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:55:51.979+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:55:51.973+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 44, in <module>
    start >> sensor >> writng >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 108, in __rrshift__
    self.__lshift__(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 98, in __lshift__
    self.set_upstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 269, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 213, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'str' object has no attribute 'update_relative'
[2023-11-18T10:55:51.983+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:55:52.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 6.150 seconds
[2023-11-18T10:56:08.359+0000] {processor.py:157} INFO - Started process (PID=3664) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:56:08.362+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:56:08.364+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:56:08.363+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:56:12.391+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:56:12.403+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:56:12.401+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 42, in <module>
    start >> sensor >> writng >> end
NameError: name 'writng' is not defined
[2023-11-18T10:56:12.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:56:12.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.074 seconds
[2023-11-18T10:56:13.462+0000] {processor.py:157} INFO - Started process (PID=3678) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:56:13.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:56:13.468+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:56:13.467+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:56:20.949+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:56:20.956+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:56:21.041+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:56:21.040+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:56:21.055+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:56:21.055+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:56:21.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 7.628 seconds
[2023-11-18T10:56:25.556+0000] {processor.py:157} INFO - Started process (PID=3732) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:56:25.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:56:25.558+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:56:25.558+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:56:29.661+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:56:29.669+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:56:29.721+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:56:29.720+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:56:29.771+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:56:29.770+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:56:29.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.239 seconds
[2023-11-18T10:57:00.497+0000] {processor.py:157} INFO - Started process (PID=3793) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:57:00.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:57:00.513+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:00.511+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:57:05.137+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:57:05.174+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:57:05.232+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:05.231+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:57:05.259+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:05.259+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:57:05.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.814 seconds
[2023-11-18T10:57:22.109+0000] {processor.py:157} INFO - Started process (PID=3832) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:57:22.112+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:57:22.115+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:22.114+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:57:27.815+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:57:27.834+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:57:27.936+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:27.936+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:57:27.947+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:27.947+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:57:27.958+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 5.855 seconds
[2023-11-18T10:57:48.614+0000] {processor.py:157} INFO - Started process (PID=3874) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:57:48.616+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:57:48.617+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:48.617+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:57:53.908+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:57:53.921+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:57:53.962+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:53.960+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:57:54.014+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:57:54.014+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:57:54.054+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 5.447 seconds
[2023-11-18T10:58:10.510+0000] {processor.py:157} INFO - Started process (PID=3920) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:58:10.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:58:10.513+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:58:10.512+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:58:14.811+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:58:14.818+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:58:14.912+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:58:14.912+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:58:14.924+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:58:14.924+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to 2022-11-12T00:00:00+00:00, run_after=2022-11-12T00:00:00+00:00
[2023-11-18T10:58:14.937+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.437 seconds
[2023-11-18T10:58:45.090+0000] {processor.py:157} INFO - Started process (PID=3992) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:58:45.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:58:45.093+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:58:45.092+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:58:48.969+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:58:48.976+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:58:49.001+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:58:49.000+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:58:49.016+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:58:49.016+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T10:58:49.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.944 seconds
[2023-11-18T10:59:19.973+0000] {processor.py:157} INFO - Started process (PID=4061) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:59:19.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:59:19.976+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:59:19.976+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:59:23.603+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:59:23.634+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:59:23.743+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:59:23.738+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:59:23.809+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:59:23.809+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T10:59:23.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.892 seconds
[2023-11-18T10:59:54.081+0000] {processor.py:157} INFO - Started process (PID=4132) to work on /opt/airflow/dags/dags.py
[2023-11-18T10:59:54.084+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T10:59:54.086+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:59:54.086+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T10:59:58.127+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T10:59:58.144+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T10:59:58.187+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:59:58.186+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T10:59:58.209+0000] {logging_mixin.py:154} INFO - [2023-11-18T10:59:58.209+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T10:59:58.220+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.147 seconds
[2023-11-18T11:00:22.207+0000] {processor.py:157} INFO - Started process (PID=4186) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:00:22.210+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:00:22.211+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:00:22.211+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:00:26.742+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:00:26.754+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:00:26.922+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:00:26.920+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:00:26.964+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:00:26.964+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:00:26.991+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.790 seconds
[2023-11-18T11:00:57.400+0000] {processor.py:157} INFO - Started process (PID=4267) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:00:57.403+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:00:57.407+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:00:57.406+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:01:00.953+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:01:00.960+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:01:00.975+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:01:00.975+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:01:00.987+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:01:00.987+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:01:00.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.608 seconds
[2023-11-18T11:01:31.602+0000] {processor.py:157} INFO - Started process (PID=4344) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:01:31.605+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:01:31.607+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:01:31.606+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:01:35.688+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:01:35.703+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:01:35.734+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:01:35.733+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:01:35.749+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:01:35.748+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:01:35.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.164 seconds
[2023-11-18T11:02:06.050+0000] {processor.py:157} INFO - Started process (PID=4404) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:02:06.063+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:02:06.066+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:02:06.065+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:02:10.453+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:02:10.460+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:02:10.475+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:02:10.475+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:02:10.489+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:02:10.489+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:02:10.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.481 seconds
[2023-11-18T11:02:41.193+0000] {processor.py:157} INFO - Started process (PID=4465) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:02:41.196+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:02:41.197+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:02:41.197+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:02:44.728+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:02:44.739+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:02:44.759+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:02:44.759+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:02:44.771+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:02:44.771+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:02:44.784+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.598 seconds
[2023-11-18T11:03:14.908+0000] {processor.py:157} INFO - Started process (PID=4534) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:03:14.910+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:03:14.911+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:03:14.910+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:03:18.342+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:03:18.359+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:03:18.388+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:03:18.387+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:03:18.407+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:03:18.407+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:03:18.419+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.516 seconds
[2023-11-18T11:03:48.651+0000] {processor.py:157} INFO - Started process (PID=4595) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:03:48.653+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:03:48.655+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:03:48.654+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:03:52.208+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:03:52.216+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:03:52.239+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:03:52.238+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:03:52.262+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:03:52.261+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:03:52.275+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.631 seconds
[2023-11-18T11:04:23.092+0000] {processor.py:157} INFO - Started process (PID=4660) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:04:23.094+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:04:23.095+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:04:23.094+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:04:26.963+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:04:26.982+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:04:27.016+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:04:27.015+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:04:27.032+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:04:27.032+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:04:27.043+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.956 seconds
[2023-11-18T11:04:57.142+0000] {processor.py:157} INFO - Started process (PID=4735) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:04:57.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:04:57.146+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:04:57.146+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:05:01.047+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:05:01.053+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:05:01.067+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:05:01.067+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:05:01.077+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:05:01.077+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:05:01.086+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.950 seconds
[2023-11-18T11:05:31.366+0000] {processor.py:157} INFO - Started process (PID=4810) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:05:31.367+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:05:31.367+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:05:31.367+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:05:34.870+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:05:34.877+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:05:34.889+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:05:34.889+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:05:34.902+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:05:34.902+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:05:34.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.548 seconds
[2023-11-18T11:06:05.089+0000] {processor.py:157} INFO - Started process (PID=4877) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:06:05.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:06:05.092+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:06:05.092+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:06:09.166+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:06:09.182+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:06:09.249+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:06:09.248+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:06:09.262+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:06:09.262+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:06:09.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.189 seconds
[2023-11-18T11:06:39.691+0000] {processor.py:157} INFO - Started process (PID=4947) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:06:39.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:06:39.699+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:06:39.697+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:06:43.614+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:06:43.619+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:06:43.634+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:06:43.634+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:06:43.656+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:06:43.656+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:06:43.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.989 seconds
[2023-11-18T11:07:14.142+0000] {processor.py:157} INFO - Started process (PID=5008) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:07:14.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:07:14.144+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:07:14.143+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:07:17.793+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:07:17.810+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:07:17.836+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:07:17.835+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:07:17.853+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:07:17.853+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:07:17.864+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.729 seconds
[2023-11-18T11:07:48.153+0000] {processor.py:157} INFO - Started process (PID=5076) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:07:48.155+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:07:48.156+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:07:48.156+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:07:52.735+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:07:52.748+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:07:52.828+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:07:52.827+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:07:52.840+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:07:52.839+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:07:52.850+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.704 seconds
[2023-11-18T11:08:23.300+0000] {processor.py:157} INFO - Started process (PID=5137) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:08:23.302+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:08:23.303+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:08:23.303+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:08:27.188+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:08:27.199+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:08:27.221+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:08:27.221+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:08:27.238+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:08:27.238+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:08:27.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.956 seconds
[2023-11-18T11:08:57.361+0000] {processor.py:157} INFO - Started process (PID=5204) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:08:57.362+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:08:57.363+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:08:57.363+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:09:01.095+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:09:01.112+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:09:01.153+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:09:01.152+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:09:01.171+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:09:01.171+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:09:01.182+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.824 seconds
[2023-11-18T11:09:31.440+0000] {processor.py:157} INFO - Started process (PID=5277) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:09:31.442+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:09:31.444+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:09:31.443+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:09:36.200+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:09:36.207+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:09:36.224+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:09:36.223+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:09:36.242+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:09:36.242+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:09:36.259+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.825 seconds
[2023-11-18T11:10:07.221+0000] {processor.py:157} INFO - Started process (PID=5357) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:10:07.223+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:10:07.225+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:10:07.224+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:10:11.486+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:10:11.512+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:10:11.600+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:10:11.599+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:10:11.671+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:10:11.671+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:10:11.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 4.492 seconds
[2023-11-18T11:10:41.814+0000] {processor.py:157} INFO - Started process (PID=5426) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:10:41.816+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:10:41.818+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:10:41.817+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:10:45.259+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:10:45.264+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:10:45.286+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:10:45.286+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:10:45.318+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:10:45.318+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:10:45.328+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.520 seconds
[2023-11-18T11:11:15.376+0000] {processor.py:157} INFO - Started process (PID=5488) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:11:15.377+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:11:15.379+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:11:15.378+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:11:19.072+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:11:19.082+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:11:19.107+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:11:19.106+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:11:19.121+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:11:19.121+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:11:19.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.760 seconds
[2023-11-18T11:11:49.323+0000] {processor.py:157} INFO - Started process (PID=5556) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:11:49.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:11:49.327+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:11:49.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:11:52.835+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:11:52.851+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:11:52.881+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:11:52.880+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:11:52.897+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:11:52.897+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:11:52.907+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.595 seconds
[2023-11-18T11:12:23.113+0000] {processor.py:157} INFO - Started process (PID=5616) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:12:23.115+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:12:23.117+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:12:23.117+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:12:26.868+0000] {logging_mixin.py:154} INFO - Error: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 65432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 65432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-11-18T11:12:26.873+0000] {processor.py:839} INFO - DAG(s) dict_keys(['wisdomise_database']) retrieved from /opt/airflow/dags/dags.py
[2023-11-18T11:12:26.885+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:12:26.885+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-18T11:12:26.897+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:12:26.897+0000] {dag.py:3722} INFO - Setting next_dagrun for wisdomise_database to None, run_after=None
[2023-11-18T11:12:26.907+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags.py took 3.801 seconds
[2023-11-18T11:12:57.117+0000] {processor.py:157} INFO - Started process (PID=5677) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:12:57.120+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:12:57.122+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:12:57.121+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:14:18.693+0000] {processor.py:157} INFO - Started process (PID=5844) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:14:18.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:14:18.698+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:14:18.697+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-11-18T11:15:40.087+0000] {processor.py:157} INFO - Started process (PID=5979) to work on /opt/airflow/dags/dags.py
[2023-11-18T11:15:40.090+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-11-18T11:15:40.091+0000] {logging_mixin.py:154} INFO - [2023-11-18T11:15:40.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
